# Generated by Django 4.2.5 on 2023-12-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerintroduction',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
