# Generated by Django 4.2.5 on 2023-12-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_alter_headerintroduction_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='firstChartDescription',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='firstChartNumber',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='fourthChartDescription',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='fourthChartNumber',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='secondChartDescription',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='secondChartNumber',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='thirdChartDescription',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='thirdChartNumber',
        ),
    ]
