# Generated by Django 4.2.5 on 2023-12-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_remove_aboutus_firstchartdescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=models.TextField(),
        ),
    ]
