# Generated by Django 4.2.5 on 2023-12-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_alter_aboutus_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstChartNumber', models.CharField(max_length=10)),
                ('firstChartDescription', models.CharField(max_length=10)),
                ('secondChartNumber', models.CharField(max_length=10)),
                ('secondChartdescription', models.CharField(max_length=10)),
                ('thirdChartNumber', models.CharField(max_length=10)),
                ('thirdChartDescription', models.CharField(max_length=10)),
                ('fourthChartNumber', models.CharField(max_length=10)),
                ('fourthChartDescription', models.CharField(max_length=10)),
            ],
        ),
    ]
