# Generated by Django 4.2.5 on 2023-12-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='firstChartDescription',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='chart',
            name='fourthChartDescription',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='chart',
            name='secondChartdescription',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='chart',
            name='thirdChartDescription',
            field=models.CharField(max_length=30),
        ),
    ]
