# Generated by Django 4.2.5 on 2023-12-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0006_alter_chart_firstchartdescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('e_mail_address', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
    ]
