# Generated by Django 4.2.5 on 2023-12-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0007_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='isMain',
            field=models.BooleanField(default=False),
        ),
    ]
