# Generated by Django 4.2.5 on 2023-12-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0008_services_ismain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='isMain',
        ),
        migrations.AddField(
            model_name='projects',
            name='isMain',
            field=models.BooleanField(default=False),
        ),
    ]
