# Generated by Django 4.2.5 on 2023-12-24 18:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0009_remove_services_ismain_projects_ismain'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='detail_description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
